### ISSUE TITLE
Broken Links - July Report

### ISSUE THREAD

**Issue by claytonjbarnette** [GSA/idmanagement.gov#1022]
## Broken Links

- [x] https://hallways.cap.gsa.gov/app/ 
  - Page: https://www.idmanagement.gov/icamsolutions/
  -  Type: slow redirect
  - Correct Link: https://acquisitiongateway.gov/
- [x] https://interact.gsa.gov/sites/default/files/mas_quarterly_summer_2019_508.pdf
  - Page: https://www.idmanagement.gov/icamsolutions/
  -  Type: redirect
  - Correct Link: https://buy.gsa.gov/interact/
- [x] https://cic.gsa.gov/
  - Page: https://www.idmanagement.gov/playbooks/cloud/
  -  Type: redirect
  - Correct Link: https://cic.gsa.gov/
- [x] https://kantarainitiative.org/what-we-do/
  - Page: https://www.idmanagement.gov/playbooks/cloud/
  -  Type: redirect
  - Correct Link: https://kantarainitiative.org/
  - Status:  fixed in PR #1020  ✅ 
- [x] https://buy.gsa.gov/api/system/files/documents/CDM%20Tools%20Product%20Ordering%20Procedure.pdf
  - Page: https://www.idmanagement.gov/icamsolutions/
  -  Type: redirect
  - Correct Link: https://buy.gsa.gov/api/system/files/documents/CDM%20Tools%20Product%20Ordering%20Procedure.pdf

**Comment by JBPayne007** [comment]
Completed.
