### ISSUE TITLE
Fix example image coding in Page Template

### ISSUE THREAD

**Issue by JillTunick** [GSA/idmanagement.gov#196]
https://github.com/GSA/idmanagement.gov/blob/staging/page-template.md

Users access this page by clicking the Page Template hyperlink in the Help Us Improve Our Content page (https://www.idmanagement.gov/contribute/)

To find the page in GitHub, scroll to the bottom of the IDM.gov repository landing page. The file, page-template.md, is a standalone file at the very bottom of the IDM.gov list of collections and files.

The example image hyperlinks in lines 118 through 122 of the page template are in an old, outdated format. Put them in this format:

`<img src="{{site.baseurl}}/assets/piv/pivauth-untrusted-ca-logon-screen.png" alt="A screenshot of a logon window that includes the words An untrusted certification authority was detected while processing the smart card certificate used for authentication." width="664" height="448">`

There is also a page-template.md file in the FICAM Playbooks repository. You may have to fix the example image links on that page, too. After you fix the example image coding in the page-template.md file in the IDM.gov repository, submit a pull request, and the updated content is published, check the page-template.md file in the FICAM Playbooks repository to see if your changes are already there. They may port over or they might not; I'm not sure if they will. If your changes haven't ported over from the page-template.md file you fixed in the IDM.gov repository, create a separate issue to fix the page-template.md file in the FICAM Playbooks repository.

**Comment by itsmohitchahal** [comment]
@JillTunick Made a pull request for this in the idmanagement.gov repository. Please check

**Comment by JillTunick** [comment]
Mohit, thank you for doing that. I created the issue for an incoming
contractor to work on, but I will point her to your solution if she has
trouble with it.

Thanks again.

Regards,

Jill Tunick
***@***.***
Supporting GSA FICAM Playbooks
CertiPath, Inc.
(703) 855-3124
