### ISSUE TITLE
Logging into https://www.myhealth.va.gov/

### ISSUE THREAD

**Issue by sitealpha** [GSA/idmanagement.gov#212]
When Loggin into https://www.myhealth.va.gov/ with ID.me or Login.gov after i go to the Secure Login Redirect screen and click accept on either page it then says the following:  Page not found

We’re sorry; we can’t find the page you're looking for. It might have been removed, had its name changed, or is otherwise unavailable.

If you typed the URL directly, check your spelling and capitalization. Our URLs look like this: www.idmanagement.gov/content-area.

Visit our homepage for helpful tools and resources, use our search bar in the upper right, submit an issue, or contact us and we’ll point you in the right direction.

Error code: 404

**Comment by idmken** [comment]
Thank you for your question. Our website does not provide any services to myhealth.va.gov. If you are having an issue logging into that service, contact their help desk, which is listed at the bottom of the page.
