### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by UNIVAC-Colonel-Panic** [GSA/idmanagement.gov#259]
**Describe the bug**
I'm attempting to get to my social secirity info. First I successfully authenticate with login.gov, do the 2FA, click on my connected accounts, click on the link for ssa.gov, get the login page, click on login.gov and get:

> Page not found
> 
> We’re sorry; we can’t find the page you're looking for. It might have been removed, had its name changed, or is otherwise unavailable.
> 
> If you typed the URL directly, check your spelling and capitalization. Our URLs look like this: www.idmanagement.gov/content-area.
> 
> Visit our homepage for helpful tools and resources, use our search bar in the upper right, submit an issue, or contact us and we’ll point you in the right direction.

**To Reproduce**
1. Go to 'https://secure.ssa.gov/RIL/'
2. Click on 'Sign in with login.gov'
3. See error

**Expected behavior**
Access to my social security info.

**Screenshots**
![Screenshot - 11_27_2022 , 9_27_29 AM](https://user-images.githubusercontent.com/492973/204151057-a6541a7a-591e-4b20-a4d2-80b13d708865.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox 

**Smartphone (please complete the following information):**
 - Version 107.0 (64-bit)

**Additional context**

**Comment by claytonjbarnette** [comment]
@UNIVAC-Colonel-Panic 
I was not able to duplicate your error, but noticed the SSA has a redesigned website: [https://beta.ssa.gov/](https://beta.ssa.gov/) that may work better for you. 

If you continue to have issues accessing the website, use this page to contact the SSA directly or locally to help you access your social security information: [https://secure.ssa.gov/ICON/main.jsp](https://secure.ssa.gov/ICON/main.jsp)
