### ISSUE TITLE
IDManagement.gov Broken Links Error Report 02172023

### ISSUE THREAD

**Issue by JBPayne007** [GSA/idmanagement.gov#291]
#### Description of Issue: ####
Broken Links Report

#### Details of Issue: ####
The following links have showed up with 404 Not Found Errors.

http://www.myexostar.com/Online-Support/
http://www.myexostar.com/Online-Support/
https://devicepki.idmanagement.gov/certificateprofiles/
https://www.gsa.gov/technology/technology-products-services/it-security/continuous-diagnostics-mitigation-cdm/continuous-diagnostics-mitigation-cdm-tools-special-item-number-sin-information-for-ordering-organizations
 
#### Pages that they are currently linked to: ####

https://www.idmanagement.gov/buy/trust-services
https://www.idmanagement.gov/buy/trust-services/
https://www.idmanagement.gov/governance/fpkiaudit/
https://www.idmanagement.gov/buy/icamsolutions/

**Comment by claytonjbarnette** [comment]
@JBPayne007 

I found the following links to resolve the broken links.

Let me know if they look like the correct destinations or need to point to another location. 

1. https://www.myexostar.com/?page_id=32 
2. https://www.myexostar.com/?page_id=32 (same link as above, only one link on the page)
3. https://devicepki.idmanagement.gov/assets/docs/US_Federal_Public_Trust_TLS_Certificate_Policy_v0_2.pdf
4. https://www.gsa.gov/technology/technology-products-services/it-security/continuous-diagnostics-mitigation-tools

**Note:** The form on this page was the closest I could find to match the [old page](https://web.archive.org/web/20180427012547/http://www.myexostar.com/Online-Support/). 
I can point 1 (1 & 2) to just the website `https://www.myexostar.com` and let the user self direct from there. if needed. 

@SuGhadiali

**Comment by claytonjbarnette** [comment]
This is the pull request #292

**Comment by JBPayne007** [comment]
Pull Request has been merged.
