### ISSUE TITLE
Link is not valid https://www.idmanagement.gov/resources/documents-and-reports/identity-and-access-management-iam/saml-v2-0-profile-for-federation-interoperability-v2-0/

### ISSUE THREAD

**Issue by samarthsaxena** [GSA/idmanagement.gov#320]
**Describe the bug**
Linke https://www.idmanagement.gov/resources/documents-and-reports/identity-and-access-management-iam/saml-v2-0-profile-for-federation-interoperability-v2-0/ shows 404 Error
![image](https://user-images.githubusercontent.com/21333710/231972403-05573997-42d9-490f-af19-c840ade70f30.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://www.idmanagement.gov/resources/documents-and-reports/identity-and-access-management-iam/saml-v2-0-profile-for-federation-interoperability-v2-0/'
2. See error

**Expected behavior**
When a link is taken down or there is a change in the endpoint of any web application. the expected way is to have the new endpoints displayed on the 404 page OR redirect the user to the new link if available.

**Screenshots**
![image](https://user-images.githubusercontent.com/21333710/231972981-83d89156-2f7d-4d2b-8f44-c66f40156610.png)

**Desktop (please complete the following information):**
 - OS: N/A
 - Browser chrome
 - Version 111.0.5563.147 

**Smartphone (please complete the following information):**
 - Device: N/A

**Additional context**
N/A

**Comment by samarthsaxena** [comment]
And there is an issue with the suggested link as well
www.idmanagement.gov/content-area
Http Error 404
![image](https://user-images.githubusercontent.com/21333710/231973949-bef5d3fc-143f-4095-a7ae-ee1dbb9489d6.png)

**Comment by claytonjbarnette** [comment]
@samarthsaxena

Please provide the page you were on and link you clicked before receiving this error

**Comment by claytonjbarnette** [comment]
No response after a week, closing issue.
