### ISSUE TITLE
0512 Identity Policy Matrix

### ISSUE THREAD

**Issue by rsherwood-gsa** [GSA/idmanagement.gov#332]
Laws, executive policies, regulations, and government standards drive multiple federal initiatives. IATAD maintains a policy matrix to map delegations and authorities. This project will update the last policy matrix and consolidate multiple policy pages on [idmanagement.gov](http://idmanagement.gov/)

**Comment by claytonjbarnette** [comment]
This is located on the new site: https://www.idmanagement.gov/university/policymatrix/
