### ISSUE TITLE
New Idea - Roadmap Page

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#342]
A new idea for the new site design could be a roadmap page—a list of coming guidance or content updates.

**Comment by claytonjbarnette** [comment]
@idmken is this something that is still wanted, if so, I need more directions to get started.

**Comment by claytonjbarnette** [comment]
@KonradMiles request this to be reassigned for tracking and more information. 


@SuGhadiali

**Comment by id2win** [comment]
@claytonjbarnette we could put a timeline right below the carousel but we dont have many artifacts planned with solid completion dates. I will think harder.

**Comment by id2win** [comment]
Thank you, we will consider this at a future date after current priority issues are resolved.
