### ISSUE TITLE
Search results page "browse site" menu has links to 404 pages

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/idmanagement.gov#35]
#### Description of Issue: ####
Search results page "browse site" menu has links to 404 pages

#### Details of Issue: ####
the "i want to", "topics" and "community" options on the search result menu result in 404

#### References (Docs, Links, Files): ####
![image](https://user-images.githubusercontent.com/57905080/126009253-6d04480e-e4fc-472e-b97f-0fe6d583e08f.png)

#### Possible Solution ####
update links to common pages (e.g. top page navigation items)

**Comment by idmken** [comment]
Hosting search results locally may fix that.

**Comment by idmken** [comment]
Updated on search.gov.
