### ISSUE TITLE
Migrate Issues from Playbooks Repo

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#367]
With the migration of playbooks.idmanagement.gov to this repo, the outstanding issues also need to migrate before making the playbooks repo a public archive.

follow these instructions to transfer - https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

@id2win

**Comment by claytonjbarnette** [comment]
Update: 

@id2win 

I checked my setting and I'm able to move issues from Playbooks repo to IDManagement.gov repo, saw your response, proceeded. 

- [x] Moved all Open issues to IDManagement.gov repo
- [x] Left Issue #953 until maybe Wednesday of next week to have a place for random comments to land, have 1 posted already.
- [x] Also added an issue [#963](https://github.com/GSA/ficam-playbooks/issues/963) about posting new issues and provide a link to the IDManagement.gov issues where they can post new and future issues.

**Stats:**  Moved 27 open issued from Playbooks repo to IDManagement.gov repo (9), now IDManagement.gov has 36 issues.

- [ ] Go through open issues moved to comment or close those that need to be closed. 
- [ ] Track issues tab on Playbooks repo to still be responsive and move any issues that come in over to IDManagement.gov
- [ ] Misc. task (any related tasks that come up)

**Question:** 
1. I moved only the open issues, do you think we need to move any closed issues or any closed up-to a certain point to provide context?
