### ISSUE TITLE
Verify new static addresses against OMB M-19-17

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#368]
OMB Memo 19-17 lists static addresses. Ensure these addresses exist to the correct content or a redirect exists to the new page.

- [ ] Examples ofICAM governance structures is available at https://www.idmanagement.gov/. 
- [ ] FICAM architecture information at HTTPS://arch.idmanagement.gov
- [ ] Information on ICAM services is available at https://arch.idmanagement.gov/services
- [ ] This list of requirements for accepting externally issued credentials is available at https://www.idmanagement.gov/.
- [ ] Approved products and services, such as those on the GSA Approved Products List (APL) are available at https://www.idmanagement.gov/.
- [ ] Information on customer facing identity services and solutions available at https://www.idmanagement.gov
- [ ] A comprehensive list of certified PKI service providers for the Federal government is available at https://www.idmanagement.gov

**Comment by b2johnsonzero7** [comment]
Clayton will work on checking that these have been checked and/or checking them, as needed.
