### ISSUE TITLE
Outlook User Guide Outdated

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#372]
The following web page is out of date:

https://playbooks.idmanagement.gov/piv/user-guide/outlook/

There is no longer a button to publish certificates to a global address list (GAL).

**Comment by id2win** [comment]
@maxwellfunk still valid and something that needs to be worked? If not we can close it out.

**Comment by maxwellfunk** [comment]
The updated link to the new page is:
https://www.idmanagement.gov/implement/outlook/

As far as I am aware the publish to GAL function is still available in Outlook 2016, I am unsure of other versions of office (e.g., 2019, 2021)

The step is not critical for usage of a PIV for email signing or encryption, but is useful for folks within the same directory.  We can either just get rid of the section, or we can put a note on there that states what the last version of office was that supported the function. 

![image](https://github.com/GSA/idmanagement.gov/assets/57905080/8c615705-d73f-46c2-9c56-92160b410efc)

**Comment by id2win** [comment]
Which approach do you recommend?

**Comment by id2win** [comment]
@maxwellfunk lets go with including the note stating the last supported version and close this one out. Thank you.

**Comment by maxwellfunk** [comment]
Confirmed that Outlook 2021 local edition also has the option for publish to GAL (see screenshot)

![image](https://github.com/GSA/idmanagement.gov/assets/57905080/bc886f96-cad0-4d8b-8bed-3ee4bf391014)

I believe O365 and newer (yearly released) versions of outlook have to be configured by microsoft cloud admins to both enable S/MIME in their mail system and subsequently the ability to publish to the directory GAL.

**Comment by id2win** [comment]
Excellent @maxwellfunk . Is that something you could change and initiate a pull request for? I would like to make sure we have the correct text along with exact location where the text needs to be. Thanks!!

**Comment by maxwellfunk** [comment]
yes, it might be a note/callout, but wanted to ensure we had the correct information as the original issue was probably specific to one implementation.
