### ISSUE TITLE
common office automation migrations

### ISSUE THREAD

**Issue by lachellel** [GSA/idmanagement.gov#374]
Agency requests for patterns for office automation migrations, including step by step for Office 365
- Reference GSA/ficam-playbooks#84 for sample explanation and two use cases
- PR GSA/piv-guides#51 being pulled out into separate branch

Currently allowed scenario is: 

1) Authentication happens on premise 
2) Assume user outside the network (not VPN into network as is - the harder scenario)
3) federated to O365
4) settings for using Alternate Login ID (and why, govt specific - related to Principal Names versus email addresses / mail, and how credentials may be used in network authentication, agencies do not need to reissue their credentials, can use as-is, etc)
5) If this works using the AltSecID mapping options for certificate based authentication, and what the settings are to configure trust for ANY certificate authority in FPKI (users crossing boundaries and not specific to one CA)

No redo of vendor specific information.  Need to clarify, govt agency focused, and all steps referenced.

**Comment by idmken** [comment]
Update, native certificate-based authentication in Azure is public preview

https://docs.microsoft.com/en-us/azure/active-directory/authentication/certificate-based-authentication-faq
