### ISSUE TITLE
ICAM Use Case - PE NPE Use Cases

### ISSUE THREAD

**Issue by smithtc1** [GSA/idmanagement.gov#375]
[ICAM Use Cases.pdf](https://github.com/GSA/ficam-arch/files/1392254/ICAM.Use.Cases.pdf)
#### Description of Issue: ####
Attached is my cut at PE and NPE Use Cases. It provides an ICAM information model that spans and aligns PE and NPE use cases over enterprise, federated and hybrid architectures based on nine conceptual ICAM processes. Four Digital Policy Management (DPM) use cases are also included.

**Comment by id2win** [comment]
https://www.idmanagement.gov/arch/#use-cases
