### ISSUE TITLE
Consolidated list of References, Standards, and Laws

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#383]
#### Description of Issue: ####
Architecture, PACS, and PM playbook all have laws, policies, and standards pages. They are in different formats with different levels of descriptions.

#### Details of Issue: ####
Potential solution could be a data yml  with all laws, policies, and standards. Create dynamic tables for each playbook based on tags in the data yml.

**Comment by idmken** [comment]
Arch - https://playbooks.idmanagement.gov/arch/standards/
PM - https://playbooks.idmanagement.gov/pm/examples/
PACS - https://playbooks.idmanagement.gov/pacs/standards/

**Comment by maxwellfunk** [comment]
potentially use a data file using topic tabs to automatically generate tables for relevant pages.

**Comment by idmken** [comment]
Check out CIO.gov as an option. https://www.cio.gov/policies-and-priorities/

**Comment by id2win** [comment]
Completed during redesign and found here - https://www.idmanagement.gov/university/policymatrix/ #413
