### ISSUE TITLE
Update Federation Section of SSO Playbook

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#385]
MVP
1. Review FICAM Roadmap federation section. Make sure all relevant points are included in SSO Federation section.
2. Incorporate open issues related to Federation or SSO.

Nice to have
1. Overview of FALs and existing methods on how to meet each.

**Comment by Krazygyrl1** [comment]
-[](https://www.id.me/)

**Comment by idmken** [comment]
- [ ] How to meet a FAL
- From NIST 800-63-3 - https://pages.nist.gov/800-63-3/sp800-63c.html

For example, 
- FAL1 maps to the OpenID Connect Basic Client profile or Security Assertion Markup Language (SAML) Web SSO Artifact Binding profile with no additional features. 
- FAL2 additionally requires that the assertion (e.g., the OpenID Connect ID Token or SAML Assertion) be encrypted to a public key representing the RP in question. 
- FAL3 requires the subscriber to cryptographically prove possession of a key bound to the assertion (e.g., the use of a cryptographic authenticator) along with all requirements of FAL2. The additional key presented at FAL3 need not be the same key used by the subscriber to authenticate to the IdP.

Regardless of what the RP requests or what the protocol requires, the RP can easily detect the FAL in use by observing the nature of the assertion as it is presented as part of the federation protocol. Therefore, the RP is responsible for determining which FALs it is willing to accept for a given authentication transaction and ensuring that the transaction meets that FAL’s requirements.

If the RP is using a front-channel presentation mechanism, as defined in [Section 7.2](https://pages.nist.gov/800-63-3/sp800-63c.html#front-channel) (e.g., the OpenID Connect Implicit Client profile or the SAML Web SSO profile), it SHALL require FAL2 or greater in order to protect the information in the assertion from disclosure to the browser or other parties in the transaction other than the intended RP.

**Comment by idmken** [comment]
@maxwellfunk can you verify a source for these OpenID Connect Basic Client profile or Security Assertion Markup Language (SAML) Web SSO Artifact Binding profile

Added to SSO playbook.

**Comment by idmken** [comment]
Best practice for applications to do access reviews may be 60-90 days. The use case is the application doesn't know if a user account stills exist in an agency SSO system.

**Comment by maxwellfunk** [comment]
@idmken just seeing this request, I think you are asking for an authoritative reference containing the profile for each, the following might work:

The OpenID Connect Basic Client Profile is available at:
https://openid.net/specs/openid-connect-basic-1_0-28.html

SAML Binding:
https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf

if you are asking if there is another authoritative mapping to FALs from NIST I would have to dig a bit deeper.

**Comment by id2win** [comment]
@maxwellfunk is this something you are helping with? If already done we can close.

**Comment by maxwellfunk** [comment]
@id2win the last comment i provided on the profiles for saml and openid connect were for ken to review.  Federation assertions and design are not my specialty, but if the links to the profiles need to be added I can faciliate help with.  I think @idmken needs to validate that fits the issue.

**Comment by maxwellfunk** [comment]
> @idmken just seeing this request, I think you are asking for an authoritative reference containing the profile for each, the following might work:
> 
> The OpenID Connect Basic Client Profile is available at: https://openid.net/specs/openid-connect-basic-1_0-28.html
> 
> SAML Binding: https://docs.oasis-open.org/security/saml/v2.0/saml-bindings-2.0-os.pdf
> 
> if you are asking if there is another authoritative mapping to FALs from NIST I would have to dig a bit deeper.

@idmken, not quite sure what you are looking for, would these links be good for the sso playbook?
