### ISSUE TITLE
Automate Subnav Building

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#386]
#### Description of Issue: ####
Subnav is manually set in the front matter. This could be time-consuming to update or maintain and potentially easily overlooked if a page is updated. The current subnav doesn't support multiple levels. On a long page, it is hard for a user to differentiate between header levels.

#### Details of Issue: ####
It is possible to automate subnav to decrease maintenance and potential errors. 

#### References (Docs, Links, Files): ####
https://www.honeybadger.io/blog/multiple-levels-of-subnavigation-with-jekyll/
https://jekyllrb.com/tutorials/navigation/#scenario-3-two-level-navigation-list

#### Possible Solution ####
1. Update the subnav.html to automate up to two or three levels of header.

**Comment by KonradMiles** [comment]
Website already at Two levels to accommodate current content layout

**Comment by KonradMiles** [comment]
Website already at Two levels to accommodate current content layout
