### ISSUE TITLE
Additional Issue to document in PIV Auth Troubleshooting guide

### ISSUE THREAD

**Issue by rsherwood-gsa** [GSA/idmanagement.gov#387]
We believe we tracked the problem down to a known issue with Microsoft Group Policy Administrative Templates. We were using those to deploy the CA certificates to all Windows systems (Domain Controllers, Servers, and Workstations). The issue comes with how GPO was deploying the certificates in that it deletes the CA certificates and adds them back every time Group Policies are run on a system. Sometimes it may not fully apply the certificates which then means the DC or workstation loses trust with the smart card certificate. If the DC loses trust  then Kerberos will tell the workstation to delete the cached credentials on the workstation. We are now deploying certificates in another manor within Group Policy as recommended by Microsoft and testing is underway.
 
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/valid-root-ca-certificates-untrusted

**Comment by id2win** [comment]
@rsherwood-gsa please advise is this is still active or can be closed.

**Comment by rsherwood-gsa** [comment]
It could be added as an alert to https://www.idmanagement.gov/implement/trust-fcpca/#use-microsoft-group-policy-object-gpo

**Comment by rsherwood-gsa** [comment]
The alert in that section should read as follows:
In some environments, under some circumstances, distribution of the root by GPO can sometimes cause PIV certificates to intermittently appear to be untrusted. Microsoft has published a description of the issue and identified a workaround in the following article: 
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/valid-root-ca-certificates-untrusted

**Comment by id2win** [comment]
@rsherwood-gsa could you add this alert if still relevant and close this out? If already complete lets close it out.
