### ISSUE TITLE
Common G2 Playbook - Cert update

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/idmanagement.gov#389]
#### Description of Issue: ####
A Common to US Treasury Root CA certificate was replaced/rekeyed after the G2 migration to incorporate the common PIV-I OIDs.  The Playbook on the G2 migration still shows the old cross certificate but could create PDVAL issues for some types of newly issued certs under Treasury.

#### Details of Issue: ####
The currently published Common --> Treasury Root CA is OBE.

#### References (Docs, Links, Files): ####
https://playbooks.idmanagement.gov/fpki/common/certificates/#issued-to-us-treasury-root-ca

#### Possible Solution ####
The certificate information and download needs to be updated at the page referenced below

#### If a New Page or Content is Needed, Expected Outcomes: ####
the new CA cert needs to be added to the cert repo, and the table containing the certificate details needs to be updated.

**Comment by techliaison** [comment]
if we update the treasury cert info we should update for other recently issued certs from the FCPCAG2 - DigiCert Federal SSP Intermediate CA G6
a decision should be made whether to just retire this playbook or maybe migrate it to something more akin to managing your trust store with instructions to distribute new certs based on cert notifications - or updating form the p7c on a periodic basis if pushing certs via GPO

**Comment by maxwellfunk** [comment]
The following page is updated with all of the certificates signed by FCPCAG2:
https://www.idmanagement.gov/implement/trust-fcpca/#certificates-issued-by-the-federal-common-policy-ca

considering this issue closed.
