### ISSUE TITLE
FPKIMA SITE map is hard to find

### ISSUE THREAD

**Issue by techliaison** [GSA/idmanagement.gov#392]
The fpki.gov site map is intuitively hard to locate in its current spot under 
https://www.idmanagement.gov/governance/fpkiaudit/#audit-information-for-the-fpki-management-authority
It would be easier to locate for people if it were listed as a useful tool in the list here
https://playbooks.idmanagement.gov/fpki/tools/

In addition it has been updated to no longer include the URLs associated with the old FCPCA
[fpki_gov_sitemap-2022-09-06.pdf](https://github.com/GSA/ficam-playbooks/files/9599176/fpki_gov_sitemap-2022-09-06.pdf)

**Comment by maxwellfunk** [comment]
@claytonjbarnette, techliaison is Wendy Brown from the FPKIMA team.  If you wouldn't mind helping develop a for to expand the useful tools table to include a row for "FPKIMA Repositories" and link to the updated sitemap document referenced here it would be helpful.  

@techliaison I think to make this useful we will need to do a permalink in the table to the document, so we might want to call the most updated document fpki_gov_sitemap.pdf and leave the date off, or else we will need to update the link every time we upload a new doc.  GitHub will actually do version control on the document itself.

**Comment by techliaison** [comment]
thanks - I don't care what the name of the file is (the date is inside the doc with a date also in Darlene's signature block.
Please make sure when it gets posted that it also replaces the current site map on the other page.  I wasn't sure if that page could just link to the same place of it should just be totally dropped from that page - maybe a Ken decision

**Comment by claytonjbarnette** [comment]
@techliaison and @maxwellfunk

This update will span two sites. The first to **IDManagement** to update the document `fpki-fpkima-sitemap.pdf` to the new version provided and archiving the previous version. The name should remain the same to help preserve any linkage from other resources.

After that, the second is to update the [**Useful Tools**](https://playbooks.idmanagement.gov/fpki/tools/) list on the **FICAM Architecture** website to include a link to the [page](https://www.idmanagement.gov/governance/fpkiaudit/#audit-information-for-the-fpki-management-authority) which contains a link to the new `fpki-fpkima-sitemap.pdf`. If the link should go directly to the PDF file, let me know.  

**Note:** The *Useful Tools* table requires four pieces of information that needs to be provided (and/or) approved: 

- **Tool:** Name of the tool
    -  Ex: `FPKIMA Repositories or “HTTP.FPKI.GOV” Site Map`
- **Link:** Anchor text, and Hyperlink to the [Page](https://www.idmanagement.gov/governance/fpkiaudit/#audit-information-for-the-fpki-management-authority)?
    - Link Text: `IDManagement.gov`
    - Hyperlink: `https://www.idmanagement.gov/governance/fpkiaudit/#audit-information-for-the-fpki-management-authority`
- **Purpose/Use:** Description of use 
   - `a descriptive purpose needs to be provided`
- **Audience:** Who should use this resource/tool
    - Ex: `FPKI Certificate Issuers or Relying Parties; System Engineers`

*The [Useful Tools](https://playbooks.idmanagement.gov/fpki/tools/) table can be used as a guide for this information.*

---

### Branches

1. Changes for the updated sitemap file can be viewed on my [0920-fpkima-sitemap](https://github.com/claytonjbarnette/idmanagement.gov/commits/0920-fpkima-sitemap) branch . 
    a. Once viewed and approved I will submit a pull request for this branch to go through first. 
3. After the above table information is determined, approved, and provided to me, I will: 
   a. Update the *Useful Tool* list on my [0920-fpki-tools](https://github.com/claytonjbarnette/ficam-playbooks/tree/0920-fpki-tools) branch for review, then submit a pull request once all is approved.

Let me know if you have any questions or comments 
@JBPayne007 and @SuGhadiali

**Comment by maxwellfunk** [comment]
@claytonjbarnette 

my personal $0.02 on your comments above:

Tool Name - I would call it "FPKIMA Repositories" as that is pretty descriptive
Link - I would go with "Consolidated Repository List" or something along that line
Purpose/Use - A consolidated list of FPKIMA repositories, to include both production and test resources
Audience - Relying Parties and System Engineers

**Comment by techliaison** [comment]
@claytonjbarnette 
@maxwellfunk 
 the PDF is only production URLs
the test URLs are already on that page in the CITE Participation Guide

**Comment by claytonjbarnette** [comment]
@maxwellfunk 
@techliaison 
Based on everything, I updated the two branches with their respective updates. 
- [0920-fpki-tools](https://github.com/claytonjbarnette/ficam-playbooks/commits/0920-fpki-tools)
- [0920-fpkima-sitemap](https://github.com/claytonjbarnette/idmanagement.gov/commits/0920-fpkima-sitemap)

Please take a moment to review and let me know if changes are needed, once all changes are approved, I will make a pull request on each branch.

**Comment by claytonjbarnette** [comment]
@techliaison @maxwellfunk 

Sorry, I missed a thread. No problem, I moved the link to the side nav *(subnav)* and named it *FPKIMA Sitemap* as a direct link to the PDF file. 😃   

- [0920-fpki-tools](https://github.com/claytonjbarnette/ficam-playbooks/commits/0920-fpki-tools)

Let me know if any additional changes are needed.  👍 

Note: The page and link will work the same no matter which order the two branches update.

**Comment by claytonjbarnette** [comment]
@techliaison 
After having to revert a few update this week for linking directly to files vs pages, (per Ken). 

To keep things consistent I need to update the [0920-fpki-tools](https://github.com/claytonjbarnette/ficam-playbooks/commits/0920-fpki-tools) branch to change the subnav link to point to the [page](https://www.idmanagement.gov/governance/fpkiaudit/#audit-information-for-the-fpki-management-authority) vs directly to the [file](https://www.idmanagement.gov/docs/fpki-fpkima-sitemap.pdf). This is to help prevent dead links in the future.(per Ken) 

I submitted the pull request for the PDF update on IDManagement.gov, so it will update first, pointing to the correct file. Then I will change the link and submit a pull request for the **0920-fpki-tools** Branch, which will the link the `subnav`  *FPKIMA Sitemap* to the [page](https://www.idmanagement.gov/governance/fpkiaudit/#audit-information-for-the-fpki-management-authority) , which has the sitemap you want people to find. 

Checking with you first to make sure this is Ok with you.  😃

**Comment by claytonjbarnette** [comment]
@techliaison following up on my last comment. 😃

**Comment by techliaison** [comment]
Sorry - I was out of the office yesterday
If it were up to me, I would prefer to see the link in the menu on the tools page directly to the file
and just remove it from the other page as no one seems to know to look for it there, if the concern is potentially having the 2 locations get out of sync with each other.

**Comment by claytonjbarnette** [comment]
@techliaison 
I think mostly the concern is about preventing dead links in the future if the file name changed. Over time it can becomes harder to track, maintain and discover broken links when this kind of linkage (across pages and sites) points to the single file.

The benefit of linking to a _Page_ is, it gets the user to the right location on the destination site, which solves (the `hard to find`) part of this issue and gives us more opportunities to provide more of the right information needed for this location and type of user if that is also an issue. 

> I do understand why and can see if that location/page was going away, why linking directly to the file would be preferred - with no one going there, this is almost the same thing, but other information lives there as well.

**Comment by idmken** [comment]
@techliaison is this document still needed? Can we post this information on idmanagement.gov somewhere? 

I know it's listed in the CPS, but having a document seems unnecessary when the website has a TLS certificate.
