### ISSUE TITLE
Identity, Credential, and Access Management Governance Framework (pdf)

### ISSUE THREAD

**Issue by ghost** [GSA/idmanagement.gov#393]
#### Details of Issue: 
•	In Appendix A: ICAM Primer (p. 28), there is a broken link: Clicking on The Office of National Intelligence Information Sharing Environment (ISE) Introduction to ICAM Principles yields a 404 error. I could not locate an exact match online.
•	In Appendix F: Policies, Standards, and Guidance (p. 36) link to FIPS 201-2 is out of date. Entry should read:

[FIPS 201-3] Federal Information Processing Standard Publication 201-3, Personal Identity Verification (PIV) of Federal Employees and
Contractors, January 2022

Linked to https://csrc.nist.gov/publications/detail/fips/201/3/final

**Comment by ghost** [comment]
https://playbooks.idmanagement.gov/docs/playbook-identity-governance-framework.pdf

**Comment by claytonjbarnette** [comment]
@jzepp I looked around for the *Appendix A:* update, but only found the following. Let me know if you think this is the correct update for this link.

- **Collaboration Page:** https://www.dni.gov/index.php/who-we-are/organizations/national-security-partnerships/ise/about-the-ise/ise-counterterrorism/123-about/1727-collaboration?tmpl=component

**Comment by idmken** [comment]
Can you make a plan to integrate this with the ICAM Program Management playbook? Schedule a brainstorm.

**Comment by ghost** [comment]
@idmken Let me evaluate the content in each and come up with some ideas/a plan. Then I'll reach out to schedule the brainstorm.

**Comment by ghost** [comment]
@idmken I've looked through the pdf and better understand the content. When do you have availability to brainstorm? Who else beyond Sutapa should attend? FYI: I am OOO Monday 1/16 and Tuesday 1/17.

**Comment by ghost** [comment]
@idmken @JBPayne007 @SuGhadiali @claytonjbarnette: I've uploaded a draft of the requested playbook integration in the ICAMSC Team Drive > FICAM Playbooks folder.

**Comment by JBPayne007** [comment]
Ok I will take a look at it. Thanks

**Comment by ghost** [comment]
You're welcome @JBPayne007. Have a great weekend!

**Comment by id2win** [comment]
This was updated during the new site development, considering closing the issue.

**Comment by JBPayne007** [comment]
Sounds good.

**Comment by id2win** [comment]
Need to figure out additional content integration.
