### ISSUE TITLE
New PIV Card Troubleshooting Error - No Valid Certs Found on This Smart Card

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#395]
#### Description of Issue: ####
User reports error on local login "No valid certificates were found on this smart card"

![image001](https://user-images.githubusercontent.com/61115074/219445056-3bc5a2d8-241f-4872-9cc5-2ac53c7fc285.png)

#### Details of Issue: ####
User reports error on local login "No valid certificates were found on this smart card"

#### References (Docs, Links, Files): ####
https://playbooks.idmanagement.gov/piv/network/troubleshooting/#name-mapping-and-piv-valdiation

#### Possible Solution ####
Potential solutions listed at https://playbooks.idmanagement.gov/piv/network/troubleshooting/#name-mapping-and-piv-valdiation

This one is not listed.

#### If a New Page or Content is Needed, Expected Outcomes: ####
Include this as another type of error after resolving the root cause.

Additionally, the accordion feature is hard to use and navigate. Consider revising to a more user-friendly help option such as headers only so you can share a direct link.

Also the diagram numbers in the main graphic don't seem to correspond to specific errors.

**Comment by idmken** [comment]
Further troubleshooting. SCinfo reads the card with no errors. It can be used for web authentication. 

Recieves the error for local authentication or RDP on domain.

**Comment by gkim01** [comment]
We are experiencing the same issue. Were you able to find a fix? 

We noticed the smart card drivers for the affected users are different. The users who are able to connect using PIV have the NIST SP 800-73 [PIV] driver. See image below for the driver configuration of a user who is able to connect using PIV.

We deleted the non-NIST driver and it reinstalls it. Microsoft won't install the NIST PIV driver. Anyone know where we can get the correct driver to test if this will resolve the issue? 

![image](https://user-images.githubusercontent.com/31216031/221925196-969fbd53-2593-4fb8-81cd-90ee49772191.png)

**Comment by idmken** [comment]
One fix.

This is a known issue for which IDEMIA asked Microsoft to halt distribution of version 1.0.0.902 yesterday around 4 AM.   We did not want or expect it to be available to customers.   The 1.2.8 version should be available again if the user updates the drivers or reinserts the smartcard.

(https://www.catalog.update.microsoft.com/Search.aspx?q=IDEMIA).

**Comment by idmken** [comment]
@gkim01 https://playbooks.idmanagement.gov/piv/gettingstarted/#middleware

**Comment by gkim01** [comment]
We fixed it yesterday by uninstalling the drivers for both the smart card and smart card reader. After uninstalling, we rebooted the affected machines, which updated with the proper drivers and it now works. Thanks!

**Comment by id2win** [comment]
Closing since the issue seems to have been fixed.
