### ISSUE TITLE
Add PIV Call-Out on determination linked to PIV.

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#396]
#### Description of Issue: ####
2020 Credentialing Standards already mentioned, perhaps as an additional talking point that is this specific point found on page 4 of the standard:

“To the maximum extent practicable, D/As must align PIV eligibility determinations with other personnel vetting determinations made by trained federal adjudicators. Individuals making PIV eligibility determinations must be investigated and adjudicated at a level commensurate with the responsibilities of the position as determined through application of the Position Designation System.”

As it pertains to “authorization”, the position designation quantifies risk and sensitivity making it the most critical factor to establish that bridge between identity and access – and often I find that folks feel like it’s a given, but the new investigative standards align well with FISMA rankings and even ISC rankings with the Low, Moderate, and High.

#### Details of Issue: ####
Add as call out in PIV Playbook as a reminder.

#### References (Docs, Links, Files): ####
https://www.opm.gov/suitability/suitability-executive-agent/policy/cred-standards.pdf

#### Possible Solution ####
Add as a call-out to maybe this section https://playbooks.idmanagement.gov/piv/#what-is-a-piv-credential

**Comment by claytonjbarnette** [comment]
@idmken is this one for me or someone else?
