### ISSUE TITLE
FPKI Graph alignment issue

### ISSUE THREAD

**Issue by rsherwood-gsa** [GSA/idmanagement.gov#435]
**Describe the bug**
The popup function for the FPKI Graph is misaligned.

**To Reproduce**
1. Go to /fpki/notifications/
1. Click on any node in the graph
1. See error

**Expected behavior**
The popup should be in the same frame as the graph

**Screenshots**
![Screenshot 2023-08-07 at 9 14 58 AM](https://github.com/GSA/idmanagement.gov/assets/88669393/68f67f77-ee77-41ef-a94e-be9851a74a1a)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Edge
 - Version 115.0.1901.188

**Comment by claytonjbarnette** [comment]
@rsherwood-gsa made adjustments to the graph CSS to realign.
