### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by RBurrhus** [GSA/idmanagement.gov#440]
The following link is broken:
https://www.idmanagement.gov/partners/trust-services/#business-identity-services

It is on the https://www.idmanagement.gov/acquisition-professionals/ page,
under the "Business Identity Services" heading,
the second bullet:
[Trust Services for Businesses](https://www.idmanagement.gov/partners/trust-services/#business-identity-services) – Approved identity and credentialing services for businesses, and which the government has approved for federated identity services.

![Screenshot 2023-08-09 123350](https://github.com/GSA/idmanagement.gov/assets/141861803/c1b22427-0f3e-41a3-84b7-ec6ea886ea4b)

**Comment by claytonjbarnette** [comment]
Link is already updated and working on staging, link will work soon, when staging is pushed to prod. 👍

**Comment by claytonjbarnette** [comment]
@RBurrhus  This link has been updated and should now point to the correct resource, which is: 

- [https://www.idmanagement.gov/trust-services/#business-identity-services](https://www.idmanagement.gov/trust-services/#business-identity-services)

Closing this issue.

**Comment by RBurrhus** [comment]
Thank you for correcting this issue. I appreciate your time and assistance.

Ray Burrhus
Unit Chief, Access Control & Responder Enrollment
Texas Division of Emergency Management
M: 512-243-4397

***@***.***
