### ISSUE TITLE
Fix Front Page Carousel for Mobile

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#454]
The front page carousel does not render appropriately for mobile. The carousel extends beyond the mobile page.

Tested on iPhone iOS 17 Safari Browser.

Solution: Fix the Carousel container to be mobile optimized.

**Comment by idmken** [comment]
fixed by #462

**Comment by KonradMiles** [comment]
- [x] Making sure display for Mobile devices (iOS / safari) works correctly

- [x] Spacing reconciliation 

- [x] Ensuring 508 Compliancy 

- [ ] Go Back and modify Text (ZeroTrust, NIST definitions  )

**Comment by claytonjbarnette** [comment]
Updated by PR #497

**Comment by claytonjbarnette** [comment]
Done, closing issue.
