### ISSUE TITLE
2021 Verification and Update Trust Services Contact Information

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#47]
Please contact each vendor or agency on the trust services page to verify contact information.

https://www.idmanagement.gov/buy/trust-services/

**Comment by maxwellfunk** [comment]
working with Matt to determine best avenue (e.g. official PA action + direct coordination, etc.)

**Comment by maxwellfunk** [comment]
Will leave this open until the next PA meeting on 9/14.

**Comment by maxwellfunk** [comment]
closing issue post FPKI PA meeting
