### ISSUE TITLE
@yaseen.aljamal@gsa.gov

### ISSUE THREAD

**Issue by yaseenaljamal** [GSA/idmanagement.gov#474]
@yaseen.aljamal@gsa.gov

_Originally posted by @yaseenaljamal in https://github.com/GSA/idmanagement.gov/issues/473#issuecomment-1683074904_

**Comment by yaseenaljamal** [comment]
[https://quickshare.samsungcloud.com/onvx8Jdm4Byj](https://quickshare.samsungcloud.com/onvx8Jdm4
Duplicate of #Byj)

**Comment by claytonjbarnette** [comment]
Closing issue
