### ISSUE TITLE
Remove Duplicate "Coming Soon" on Phishing Resistant Carousel Page

### ISSUE THREAD

**Issue by KonradMiles** [GSA/idmanagement.gov#505]
- [x] Remove "Coming Soon!" from Phishing resistant Carousel Page.  Only leave the "(Coming soon)" after 'Phishing resistant authenticators'

It's in the Blue fill and white letter on the homepage 

[](https://www.idmanagement.gov/)

**Comment by claytonjbarnette** [comment]
Updated in PR #506
