### ISSUE TITLE
Broken link for entrust manages services root CA

### ISSUE THREAD

**Issue by id2win** [GSA/idmanagement.gov#550]
Please investigate and validate link with FPKI team and fix based on their recommendation if appropriate. 

The link for the Entrust Managed Services Root CA](https://www.idmanagement.gov/implement/trust-fcpca/#issued-to-entrust-managed-services-root-ca) @ https://www.idmanagement.gov/implement/certs/Entrust_Managed_Services_Root_CA_rekey.cer does not match the SHA256 thumbprint listed on the webpage.

**Comment by maxwellfunk** [comment]
Issue #549 is already generated to correct this.  It has to do with PEM vs base-64 formatting for the certificate.  Closign this issue
