### ISSUE TITLE
Validate FPKI crawler works per the user guide instructions 

### ISSUE THREAD

**Issue by id2win** [GSA/idmanagement.gov#598]
Crawler SOP was created by FPKI SME. Validation by someone other than the creator is required to ensure it works as intended. Please follow the instructions and provide input on outcomes and lessons learned no later than noon COB on 10-5. SOP is within the team SOP folder.

**Comment by TheInfinityBeyonder** [comment]
Tested the Crawler to the designated stopping point. The suggestions made will be verified, the necessary updates to the SOP will be made, and submitted for final QA. @SuGhadiali @claytonjbarnette  @id2win  @KonradMiles
