### ISSUE TITLE
Accessibility - add HTML sitemap

### ISSUE THREAD

**Issue by id2win** [GSA/idmanagement.gov#626]
Accessibility focus: HTML site maps
"Does your website have an HTML site map? If not, consider adding one. Site maps are recommended by WCAG, and they improve search engine optimization."

- [x] Add sitemap
- [x] Review in preview

**Comment by claytonjbarnette** [comment]
@id2win this is a WIP towards preview.

**Comment by claytonjbarnette** [comment]
# Stiemap.xml Preview
@id2win @KonradMiles 

This is ready for preview, I added back the `sitemap.xml` file and updating the listing that is displayed. 
- The old listing displayed a small part of the site
- The new listing displays all main links along with their internal page links:
  - which link to important information with headers inside pages on our site). 
 
 Improvement: better listing of what is on the website for better indexing.

- The new sitemap.xml can be viewed here [View](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/1030-sitemap-preview/sitemap.xml)

Let me know next step. 

@SuGhadiali @TheInfinityBeyonder

**Comment by claytonjbarnette** [comment]
@KonradMiles @id2win 
This has been completed and active on the site.
