### ISSUE TITLE
System Notification for: FCPCAG2

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/idmanagement.gov#640]
Notice Date: October 25, 2023
System: FPKI Trust Infrastructure - Federal Common Policy CA G2
Type: CA Certificate Issuance
Change Description: The Federal Common Policy CA G2 intends to issue a new cross certificate to the U.S. Department of State AD Root CA between 11/08/2023 and 11/15/2023
Contact: fpki dash help at gsa dot gov
Certificate Issuer: CN=Federal Common Policy CA G2, OU=FPKI, O=U.S. Government, C=US
Certificate Subject: CN=U.S. Department of State AD Root CA, CN=AIA, CN=Public Key Services, CN=Services, CN=Configuration, DC=state, DC=sbu
Certificate SHA1 Hash: N/A
Certificate Revocation List: http://repo.fpki.gov/fcpca/fcpcag2.crl  
Certificate Bundle (AIA): http://repo.fpki.gov/fcpca/caCertsIssuedTofcpcag2.p7c  
Certificate Bundle (SIA): http://crls.pki.state.gov/SIA/CertsIssuedByADRootCA.p7c  
OCSP: N/A
EE CRL DP: N/A
EE OCSP: N/A

**Comment by dproudGSA** [comment]
Closed by PR #645
