### ISSUE TITLE
Config Guide for Azure CBA with PIV

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#668]
A few agencies have asked for help in how to configure Microsoft Azure and Okta for certificate-based authentication with PIV.

**Comment by id2win** [comment]
Working with OPM and ED on CBA and PIV; exploring agencies for CBA and Okta.

**Comment by idmken** [comment]
Basic overview for a USAccess PIV

FCPCA G2
Root - Self-Signed
Subject CRL: http://repo.fpki.gov/fcpca/fcpcag2.crl
Thumb: 99b4251e2eee05d8292e8397a90165293d116028

For PIV Issued before August 13, 2019
August 13, 2019< - Entrust Root to Entrust Root (This links to the Entrust Root listed above)
Intermediate
Subject CRL: http://feddcsweb.managed.entrust.com/CRLs/EMSRootCA2.crl
Thumb: 855d98c924b3ee6216b1b8e25b4342f70565c394
August 13, 2019< - Entrust Root to Entrust SSP
Intermediate - Issuing CA
Subject CRL: http://feddcsweb.managed.entrust.com/CRLs/EMSSSPCA2.crl
Thumb: dec01bf40c153fbc38bf2ca766b04f9dfbda3064

For PIV Issued after August 13, 2019
August 13, 2019> - FCPCA G2 to Entrust Root
Intermediate
Subject CRL: http://rootweb.managed.entrust.com/CRLs/EMSRootCA3.crl
Thumb: 07f5dc58f83778d5b5738a988292c00a674a0f40
August 13, 2019> - Entrust Root to Entrust SSP
Intermediate - Issuing CA
Subject CRL - http://sspweb.managed.entrust.com/CRLs/EMSSSPCA3.crl
722e8abbe6b66e47d1bcec3c7ec47aa5bbe4d3c5

For PIV issued After July 13, 2023
August 13, 2019> - FCPCA G2 to Entrust Root
Intermediate
Subject CRL: http://rootweb.managed.entrust.com/CRLs/EMSRootCA4.crl
d6be623683f2b47e94452c04fa1ab3ab631e83eb 
August 13, 2019> - Entrust Root to Entrust SSP
Intermediate - Issuing CA
Subject CRL - http://sspweb.managed.entrust.com/CRLs/EMSSSPCA4.crl
19fea49c468760edce9600a9da9657b484734d24

Microsft CBA instructions - https://learn.microsoft.com/en-us/azure/active-directory/authentication/how-to-certificate-based-authentication

**Comment by idmken** [comment]
Instead of static PKI information, link to the information in the https://github.com/GSA/idmanagement.gov/blob/staging/_data/fpkicustomers.yml

Also update this yml with static information from https://www.idmanagement.gov/fpki/notifications/#active-issuing-ca-certificate-details

**Comment by idmken** [comment]
Maybe convert the PIV Issuer information table into an accordion that includes the CA information.

**Comment by id2win** [comment]
Providing final guide content to @TheInfinityBeyonder for page creation within the IDM.
