### ISSUE TITLE
Remove all US GPO references from IdManagment.gov site

### ISSUE THREAD

**Issue by JBPayne007** [GSA/idmanagement.gov#727]
Removal of all US GPO references from IdManagement.gov site. 

Per email from Matt and John Hannan US GPO

Request that our team remove all references to the GPO PKI as an SSP PKI option from the FPKI web pages,

No later than second week of JAN 2024.

**Comment by maxwellfunk** [comment]
Luckily the GPO certificate expired in September 2023 and as a result has dropped off of the FPKI crawler (automatically removed 3 months ago).  

There is no mention of GPO on the trust services page as they are not a SSP:
https://www.idmanagement.gov/trust-services/

They are also not mentioned in the PIV issuing CAs:
https://www.idmanagement.gov/fpki/notifications/#piv-issuer-information

The final remaining reference is on the FPKI audit information table, we will only have to remove one row:
https://www.idmanagement.gov/fpki/#annual-review-schedule

We may need to remove GPO references from the following digital signature playbook as they no longer provide signing certificates for the OFR:
https://www.idmanagement.gov/playbooks/signfedregister/
