### ISSUE TITLE
Quality Assurance - Diagnose Level 2 and Level 3 Broken Links 

### ISSUE THREAD

**Issue by KonradMiles** [GSA/idmanagement.gov#751]
About the Issue:

Leveraging SiteImprove a Broken Link report was generated consisting of roughly 2 instances. 2 broken links are cert revocation files, downloadable so not the general url.

How to fix:

A Spreadsheet was provided in email which links to a Google Sheets Document within the FICAM Architecture and Design Team shared Drive.

Click on a page title to be taken to the Page Report. From there you can see exactly where the broken links are on the page and in your source code. If you have CMS deep linking set up, you can go straight to your CMS to fix it.

**Comment by JBPayne007** [comment]
Completed.
