### ISSUE TITLE
Website Content Updates - Update FIBF Timeline Image on IDManagement Website

### ISSUE THREAD

**Issue by KonradMiles** [GSA/idmanagement.gov#762]
Ask:

Working with FIBF team, content was added to the IDManagement website to support the FIBF website. (An Image was added)

Requests for the [ICAM FIBF page](https://www.idmanagement.gov/icam-fibf/):

Can we update the quality of the image on the "The Draft ICAM FIBF" paragraph?  (See Attached file)

![FBIF Components Timeline v5 (3)](https://github.com/GSA/idmanagement.gov/assets/142627376/5743592e-107c-44ed-8016-d40deee2cb2e)

**Comment by JBPayne007** [comment]
New Image to be used sent from Vanessa.
![FIBF Timeline Graphic 1020x560 Light Verison (2) (3)](https://github.com/GSA/idmanagement.gov/assets/77509173/99b44f6a-1e2c-42e3-b619-b775b072dfe2)

**Comment by JBPayne007** [comment]
Updated image as requested and merged into Staging.
