### ISSUE TITLE
Website Content Updates - Add a FIBF Announcement to the carousel on the main page

### ISSUE THREAD

**Issue by KonradMiles** [GSA/idmanagement.gov#763]
Ask:

Working with FIBF team, content was added to the IDManagement website to support the FIBF website. (An Image was added)

Requests for the [ICAM FIBF page](https://www.idmanagement.gov/icam-fibf/):

Add a FIBF Announcement to the carousel on the main page of the [idmanagement.gov](http://idmanagement.gov/) site?
The ICAM FIBF WG has completed Component 1: Business Lifecycle, Functions and Activities and has kicked off the development of Component 2: Business Capabilities. For more information on the latest ICAM FIBF developments check out the ICAM FIBF web page.

**Comment by claytonjbarnette** [comment]
@JBPayne007  @KonradMiles  @SuGhadiali 

Created a dev branch with FIBF added to the Carousel:  [0131-fibfwg-carousel](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0131-fibfwg-carousel/). Let me know if it is good to go.

**Comment by KonradMiles** [comment]
Per consultation with Clayton Barnette and Vanessa Arias in ChatOps, the content edits for the FIBF main page resolve and close this issue
