### ISSUE TITLE
Move FPKI Key Recovery Policy document to archive

### ISSUE THREAD

**Issue by dproudGSA** [GSA/idmanagement.gov#767]
The FPKI Key Recovery Policy document has been rolled into the Common and Bridge policies and, therefore, can be archived. The direct link to the document is: https://www.idmanagement.gov/docs/fpki-key-recovery.pdf 
It is located in the https://www.idmanagement.gov/fpki/#federal-pki-policies-and-profiles section.

**Comment by claytonjbarnette** [comment]
## Update: 
- Removed `FPKI Key Recovery` paragraph from page: `fpki/` page
- Archived: `docs/fpki-key-recovery.pdf` file 
  - Moved to: `docs/archived/fpki-key-recovery_20240205.pdf`
- Pushed changes to [dev branch](): `0205-archive-key-recovery-doc` for review.

@SuGhadiali 
@dproudGSA

**Comment by dproudGSA** [comment]
Do you have a branch where I can preview the changes? @claytonjbarnette

**Comment by dproudGSA** [comment]
@claytonjbarnette We need to add a tombstone comment indicating that this document has been subsumed into the Common and Bridge policy documents as of 2021.

**Comment by claytonjbarnette** [comment]
@dproudGSA  @SuGhadiali 

I have updated the F PKI Document Archives:

- See Heading: `Federal Public Key Infrastructure Key Recovery Policy`
- See: [FPKI Key Recovery Policy](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0205-archive-key-recovery-doc/docs/archived/fpki-key-recovery_20240205.pdf)

Let me know if it is good to go. 

Clayton

**Comment by maxwellfunk** [comment]
Reopened to provide for adding a tombstone page to the archived KRP document.

Additionally, wanted to extend the time before removal of the document from the archive table and include it as its own sub-bullet of archived documents under supplemental FPKI guidance section.
