### ISSUE TITLE
System Notifications for: WidePoint SSP

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/idmanagement.gov#768]
3 Notices in one issue (intent, issuance, and intent to revoke)

notice_date:  February 1, 2024
system: FPKI Trust Infrastructure - Federal Common Policy CA G2
change_type:  Intent to Revoke a CA Certificate
change_description: On or about March 4, 2024 the Federal Common Policy CA G2 intends to revoke a dated instance of the WidePoint ORC SSP 5 CA in support of the recent certificate modification (certificate serial number 210b3f17db750e616eb25f3f0b4933e5a98c449b)
contact: fpki dash help at gsa dot gov
ca_certificate_issuer: CN=Federal Common Policy CA G2, OU=FPKI, O=U.S. Government, C=US
ca_certificate_subject: CN=WidePoint ORC SSP 5, O=ORC PKI, C=US
ca_certificate_hash: 80f4731a60fd5f2eb0468d0629310daa50ad210d
ca_cdp_uri: http://repo.fpki.gov/fcpca/fcpcag2.crl
ca_aia_uri: http://repo.fpki.gov/fcpca/caCertsIssuedTofcpcag2.p7c
ca_sia_uri: http://crl-server.orc.com/caCerts/WidePointORCSSP5.p7c
ca_ocsp_uri: N/A
ee_cdp_uri: http://crl-server.orc.com/CRLs/WIDEPOINTORCSSP5.crl
ee_ocsp_uri:  http://ssp5.eva.orc.com

notice_date:  February 1, 2024
system: FPKI Trust Infrastructure - Federal Common Policy CA G2
change_type:  CA Certificate Issuance
change_description: The Federal Common Policy CA G2 issued a modified to WidePoint ORC SSP 5 which includes Derived PIV policies
contact: fpki dash help at gsa dot gov
ca_certificate_issuer: CN=Federal Common Policy CA G2, OU=FPKI, O=U.S. Government, C=US
ca_certificate_subject: CN=WidePoint ORC SSP 5, O=ORC PKI, C=US
ca_certificate_hash: e4776896b9a21e65b86d07034d0e231c0bced192
ca_cdp_uri: http://repo.fpki.gov/fcpca/fcpcag2.crl
ca_aia_uri: http://repo.fpki.gov/fcpca/caCertsIssuedTofcpcag2.p7c
ca_sia_uri: http://crl-server.orc.com/caCerts/WidePointORCSSP5.p7c
ca_ocsp_uri: N/A
ee_cdp_uri: http://crl-server.orc.com/CRLs/WIDEPOINTORCSSP5.crl
ee_ocsp_uri:  http://ssp5.eva.orc.com

notice_date:  January 18, 2024
system: FPKI Trust Infrastructure - Federal Common Policy CA G2
change_type:  CA Certificate Issuance
change_description: The Federal Common Policy CA G2 intends to issue a modified certificate for PIV Derived Policies to WidePoint ORC SSP 5 between 2/1/2024 and 2/8/2024.  Once the new certificate is accepted and published the previous certificate will be revoked.
contact: fpki dash help at gsa dot gov
ca_certificate_issuer: CN=Federal Common Policy CA G2, OU=FPKI, O=U.S. Government, C=US
ca_certificate_subject: CN=WidePoint ORC SSP 5, O=ORC PKI, C=US
ca_certificate_hash: 80f4731a60fd5f2eb0468d0629310daa50ad210d
ca_cdp_uri: http://repo.fpki.gov/fcpca/fcpcag2.crl
ca_aia_uri: http://repo.fpki.gov/fcpca/caCertsIssuedTofcpcag2.p7c
ca_sia_uri: http://crl-server.orc.com/caCerts/WidePointORCSSP5.p7c
ca_ocsp_uri: N/A
ee_cdp_uri: http://crl-server.orc.com/CRLs/WIDEPOINTORCSSP5.crl
ee_ocsp_uri:  http://ssp5.eva.orc.com

**Comment by dproudGSA** [comment]
Closed by #771
