### ISSUE TITLE
Remove duplicate image from assets: framework-comment-timeline.PNG

### ISSUE THREAD

**Issue by claytonjbarnette** [GSA/idmanagement.gov#790]
**ISSUE:**
The image: `framework-comment-timeline.PNG` in the `assets/img/` folder is competing with the image that replaced it `framework-comment-timeline.png` on file systems using Git on the command line. 

**Solution:**
Remove [framework-comment-timeline.PNG](https://www.idmanagement.gov/assets/img/framework-comment-timeline.PNG) to prevent this file conflict, leaving [framework-comment-timeline.png](https://www.idmanagement.gov/assets/img/framework-comment-timeline.png) as the main image used on the [https://www.idmanagement.gov/icam-fibf/](https://www.idmanagement.gov/icam-fibf/) page.

**Comment by JBPayne007** [comment]
That would be great. I tried to remove this duplicate image last week and it would not allow it.
