### ISSUE TITLE
Accessibility - ICAMSC page and links update

### ISSUE THREAD

**Issue by JBPayne007** [GSA/idmanagement.gov#822]
1. On the [ICAMSC page](https://www.idmanagement.gov/ficam/) - can you update the following wording and Connect.gov link and upload the attached signed ICAMSC Charter (PDF)
Membership and Meetings (OLD wording)
Membership is open to federal agency employees with a .gov or .mil email address. Contractors are permitted to join on a case-by-case basis. See the [ICAMSC Meeting Page on Max.gov](https://login.max.gov/cas/login?service=https%3A%2F%2Fcommunity.max.gov%2Flogin.action%3Fos_destination%3D%252Fpages%252Fviewpage.action%253FpageId%253D234815732)for more information. Access to the page requires a multifactor authentication using either Max Secure+ or a PIV/CAC.

Membership and Meetings (NEW wording along with new Connect.gov link and PDF)
Membership is open to federal agency employees with a .gov or .mil email address. Contractors are permitted to join on a case-by-case basis. See the [ICAMSC Meeting Page on Connect.gov](https://community.connect.gov/display/Egov/ICAMSC+Meeting+Materials)for more information. Access to the page requires a multifactor authentication using a PIV/CAC. See the ICAMSC Charter (PDF, September 2023) for information on membership requirements, voting rights, etc.

2. Under the FICAM Program, in the ["Identity, Credential, and Access Management Subcommittee"](https://www.idmanagement.gov/ficam/#identity-credential-and-access-management-subcommittee) subsection update the following text: 

(OLD)
The ICAMSC is co-chaired by the [GSA Office of Government-wide Policy](https://www.gsa.gov/about-us/organization/office-of-governmentwide-policy) and another volunteer agency (currently the Department of Justice). The ICAMSC aligns the identity management activities of the federal government and supports collaborative government-wide efforts to:

(NEW)

The ICAMSC is co-chaired by the [GSA Office of Government-wide Policy](https://www.gsa.gov/about-us/organization/office-of-governmentwide-policy), Department of Justice and 
Department of Homeland Security, CISA. The ICAMSC 
aligns the identity management activities of the federal government and 
supports collaborative government-wide efforts to:

**Comment by JBPayne007** [comment]
[202309-charter-icamsc.pdf](https://github.com/GSA/idmanagement.gov/files/14451390/202309-charter-icamsc.pdf)

**Comment by JBPayne007** [comment]
Update for the last part to write out CISA instead of using the acronym.
(NEW)

The ICAMSC is co-chaired by the [GSA Office of Government-wide Policy](https://www.gsa.gov/about-us/organization/office-of-governmentwide-policy), Department of Justice and 
Department of Homeland Security, Cybersecurity and Infrastructure Security Agency. The ICAMSC

**Comment by claytonjbarnette** [comment]
@JBPayne007 

Does `202309-charter-icamsc.pdf` replace `fpkipa-charter.pdf`?

**Comment by JBPayne007** [comment]
No they are two different groups.

**Comment by JBPayne007** [comment]
Only the ICAM-SC group charter has changed to a community of practice.

**Comment by claytonjbarnette** [comment]
I need a location on the page to place the link and link text.

**Comment by JBPayne007** [comment]
Yeah kind of tricky, From my first comment above the pdf link should be the following. 
**See the ICAMSC Charter (PDF, September 2023)**

**Comment by JBPayne007** [comment]
So I would word the pdf link as ICAMSC Charter September 2023.
