### ISSUE TITLE
Why not use AMA for privileged users

### ISSUE THREAD

**Issue by f-bader** [GSA/idmanagement.gov#824]
I would like to better understand the reasoning for the following note in the "Configure Smart Card Logon on Windows Domains" guide

```
Do not use AMA to provide privileged user access
```

I understand there are certain scenarios where it might not act as expected, but for users in e.g. protected this should be mitigated.

https://support.microsoft.com/en-gb/topic/description-of-ama-usage-in-interactive-logon-scenarios-in-windows-a61e0931-f11a-73ad-6221-e117ed6e913f

Thank you very much in advance

**Comment by idmken** [comment]
Thanks, @f-bader. I'll try to find the author and get back to you. Is your recommendation to allow AMA for privileged users?

**Comment by idmken** [comment]
These are earlier versions of the warning.
- 7 years ago - Do not use AMA to provide privileged user access to servers without another access control method in combination with AMA. https://github.com/GSA/piv-guides/blame/f02a346111acf949d1d6fcaf4ce32220a63ac299/_networkconfig/10_AMA.md#L12
- 6 years ago - Do not use AMA to provide privileged user access via single sign on for any privileged actions. https://github.com/GSA/piv-guides/blame/88a05d28d6316de843d5dacda2150c372457507c/_networkconfig/10_ama.md#L19

**Comment by f-bader** [comment]
To answer your question about my opinion here as well:

I think AMA is a great addition if the privileged user is already protected by SCRIL and member of the protected users group.

This (IMHO) will mitigate all the shortcomings mentioned in this article by Microsoft on edge cases that "bypass" the AMA logic

https://support.microsoft.com/en-gb/topic/description-of-ama-usage-in-interactive-logon-scenarios-in-windows-a61e0931-f11a-73ad-6221-e117ed6e913f

But I found this warning I was curious if I missed a crucial thing that would rule out the usage

**Comment by idmken** [comment]
@f-bader from checking the history on content. It sounds like the best practice for privileged users is to use a separate account and the highest available authenticator at all times. So, using AMA where enforcing different levels for different resources is unnecessary. I can update the page with it.

**Comment by f-bader** [comment]
Thank you @idmken for following up and clarifying. Those make a lot of sense 👍
