### ISSUE TITLE
Quality Assurance - Update Azure AD references

### ISSUE THREAD

**Issue by idmken** [GSA/idmanagement.gov#848]
On the WHfb and new CBA page.

- [x] replace Azure or Azure Entra ID with Entra Id.
When it comes to Entra Hybrid Joined devices a device signal is one of the following:
- [x] Entra Hydrid Joined – means the device is AD joined and managed via GPO/SCCM (no explicit validation, it’s the org’s responsibility to make sure it is properly managed)
- [x] Compliant device – means the device is either cloud managed (Intune or supported MDM partner) or co-managed (Intune + SCCM).

**Comment by claytonjbarnette** [comment]
@idmken  The first task listed above is ready for review on [0320-entra-update-848](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0320-entra-update-848/).

-  [cba-azure](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0320-entra-update-848/implement/cba-azure/)
- [whfb](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0320-entra-update-848/implement/whfb/)

After looking, on these two pages I found other products and services that were also affected by the product renaming. I renamed those as well using the links below as a guide. 

- [Glossary of updated terminology](https://learn.microsoft.com/en-us/entra/fundamentals/new-name#glossary-of-updated-terminology) (50+)
- [Display names, service plans and SKUs](https://learn.microsoft.com/en-us/entra/fundamentals/new-name#what-are-the-display-names-for-service-plans-and-skus) (14)
- [Microsoft Entra Kerberos](https://learn.microsoft.com/en-us/azure/storage/files/storage-files-identity-auth-hybrid-identities-enable?tabs=azure-portal) (referenced for naming only)
- [Microsoft Entra hybrid joined devices](https://learn.microsoft.com/en-us/entra/identity/devices/concept-hybrid-join) (referenced for naming only)

> I went with their recommended naming since that is what may get searched and aid in page listings in search results.  

 Let me know if I need to do a second pass to tone down the MS branding portion of their renaming. 👍 

@SuGhadiali 
@JBPayne007

**Comment by claytonjbarnette** [comment]
ℹ️ Item 2 and 3 completed in MSFT Review CBA Doc #853 

@SuGhadiali 
@JBPayne007

**Comment by claytonjbarnette** [comment]
@idmken 

Requesting a review of this update, changes in branch [0320-entra-update-848](https://github.com/GSA/idmanagement.gov/tree/0320-entra-update-848).

- [cba-azure](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0320-entra-update-848/implement/cba-azure/)
- [whfb](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0320-entra-update-848/implement/whfb/)

@JBPayne007 
@SuGhadiali

**Comment by claytonjbarnette** [comment]
@idmken  do you have a moment to review the [0320-entra-update-848](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0320-entra-update-848/) dev branch before I submit the PR? ☕ 

@SuGhadiali 
@JBPayne007

**Comment by idmken** [comment]
Sorry, I think this was already updated.
