### ISSUE TITLE
Accessibility - Remove confusing language regarding the scope of PIV testing for the FPKI Annual Review Page

### ISSUE THREAD

**Issue by rsherwood-gsa** [GSA/idmanagement.gov#851]
https://github.com/GSA/idmanagement.gov/blob/53caf642f562e9aa12b9537db358c74a07589ab0/_ficampmo/fpki.md?plain=1#L67

Currently, this page includes the following language:

> PIV and PIV-I Annual Testing - supports FPKI Annual Reviews and can be done either in person at the GSA [FIPS 201 Lab](https://www.idmanagement.gov/fips201ep/#personal-identity-verification-credentials) or using available tools such as the [Card Conformance Tool (CCT) and Certificate Profile Conformance Tool (CPCT)](https://www.idmanagement.gov/fpki/#compliance-test-tools-for-annual-reviews)

This is creating confusion for some affiliates, who are interpreting this to mean that the CCT test is the only requirement for PIV testing. I recommend replacing this text with the following:

PIV and PIV-I Annual Testing - supports FPKI Annual Reviews and can be done either in person at the GSA [FIPS 201 Lab](https://www.idmanagement.gov/fips201ep/#personal-identity-verification-credentials) or remotely by the package submitter. In either case, the requirements for testing are documented [here](https://www.idmanagement.gov/fips201ep/#personal-identity-verification-credentials).

**Comment by claytonjbarnette** [comment]
@rsherwood-gsa  I reworded the last sentence to provide more accessibility context to the link text. Let me know if that language is OK. 

@SuGhadiali
