### ISSUE TITLE
Quality Assurance - May Broken Links 

### ISSUE THREAD

**Issue by KonradMiles** [GSA/idmanagement.gov#951]
About the Issue:

Leveraging SiteImprove a Broken Link report was generated consisting of roughly 6 instances. 6 broken links are cert revocation files, downloadable so not the general url.

How to fix:

A Spreadsheet was provided in email which links to a Google Sheets Document within the FICAM Architecture and Design Team shared Drive.

Click on a page title to be taken to the Page Report. From there you can see exactly where the broken links are on the page and in your source code. If you have CMS deep linking set up, you can go straight to your CMS to fix it.

**Comment by claytonjbarnette** [comment]
## Update:

- 4 updated by @TheInfinityBeyonder and confirmed working.
- 2 fixed after review, confirmed working.
- Updated links pushed to staging -> prod. 
- Result: All 6 links pushed to prod. 
- Closed by #958 and #959 

@SuGhadiali 
@TheInfinityBeyonder 
@KonradMiles
