### ISSUE TITLE
Additional Issues in IA Control Mapping Comments

### ISSUE THREAD

**Issue by TheInfinityBeyonder** [GSA/idmanagement.gov#970]
https://github.com/GSA/idmanagement.gov/blob/b9c94ee011fdcb18c64b06463dfb0628d298d28f/security-controls-mapping3.md?plain=1#L285

This statement is broken out below, and the sub-requirements are addressed individually.

https://github.com/GSA/idmanagement.gov/blob/b9c94ee011fdcb18c64b06463dfb0628d298d28f/security-controls-mapping3.md?plain=1#L1746

"Accept and electronically verify Personal Identity Verification-compliant credentials from other federal agencies."

https://github.com/GSA/idmanagement.gov/blob/b9c94ee011fdcb18c64b06463dfb0628d298d28f/security-controls-mapping3.md?plain=1#L1791

"Accept and verify federated or PKI credentials that meet [Assignment: organization-defined policy]."

https://github.com/GSA/idmanagement.gov/blob/b9c94ee011fdcb18c64b06463dfb0628d298d28f/security-controls-mapping3.md?plain=1#L3203

Question for the group - does this apply to applications that don't do identity proofing, such as RPs? Should we distinguish in the mapping?

https://github.com/GSA/idmanagement.gov/blob/b9c94ee011fdcb18c64b06463dfb0628d298d28f/security-controls-mapping3.md?plain=1#L5559

PSTN has been deprecated for government use.

https://github.com/GSA/idmanagement.gov/blob/b9c94ee011fdcb18c64b06463dfb0628d298d28f/security-controls-mapping3.md?plain=1#L6499

What is the role of these authenticators with regard to the mapping?

https://github.com/GSA/idmanagement.gov/blob/b9c94ee011fdcb18c64b06463dfb0628d298d28f/security-controls-mapping3.md?plain=1#L7350

Is this related to IA-5 f. (changing or refreshing an authenticator)?

**Comment by JBPayne007** [comment]
Didn't receive stakeholder feed back on items.
