### ISSUE TITLE
Okta / Yubikey Implementation Guide

### ISSUE THREAD

**Issue by JBPayne007** [GSA/idmanagement.gov#975]
Hello Team,

Please see the documents attached from the FICAM Arch chat. we have the final draft for Okta and Yubikey implementation guide ready, please work with the team to get the information onto IDM under the implement section. Each document is numbered to provide a numeral flow of content for the web page. Please mask the CMS logo or crop it out for screenshots that show CMS. Looking forward to reviewing the preview page no later than Wednesday next week.
Also please use the same formatting as the CBA guide, including agency logos up top etc.

**Comment by claytonjbarnette** [comment]
Branch ready for review 👀 

[Okta / Yubikey Implementation Guide](https://federalist-cf03235f-a054-4178-aafb-4e1e61e0d42c.sites.pages.cloud.gov/preview/gsa/idmanagement.gov/0603-yubikey-guide/implement/yuvikey-guide/)
