### ISSUE TITLE
Updates to ZT adoption page

### ISSUE THREAD

**Issue by TheInfinityBeyonder** [GSA/idmanagement.gov#985]
On Page: [FICAM is the foundation for ZT adoption (idmanagement.gov)](https://www.idmanagement.gov/zero-trust/#ficam-alignment-to-cisa-zero-trust-maturity-model)

- Zero trust alignment > Defined - internal side navigation link not working
- `</table>`  text showing under ‘ functions and guidance’ heading
- `</ul> </td> </tr>` text showing in FICAM guidance table column

**Comment by claytonjbarnette** [comment]
ZT Page Updates: 
- [x] - Zero trust alignment > Defined - internal side navigation link not working
- [x] - `</table>` text showing under ‘ functions and guidance’ heading
- [x] - `</ul> </td> </tr>` text showing in FICAM guidance table column

> **Note:** HTML was missing a closing anchor tag `</a>` on the third bullet point, which fixed item 2 and 3.
