### ISSUE TITLE
NIST Publication for SP 800-32 Manage link broken

### ISSUE THREAD

**Issue by wkctech-PGWiCyS** [GSA/idmanagement.gov#986]
**Describe the bug**
The NIST publication link goes to a page not found.
https://www.idmanagement.gov/manage/

**Comment by wkctech-PGWiCyS** [comment]
https://csrc.nist.gov/news/2021/withdrawal-of-nist-special-pubs-800-15-25-and-32

**Comment by claytonjbarnette** [comment]
@PG-WiCyS-wkctech 

An updated address for the [link](https://www.idmanagement.gov/manage/) producing the 404 on NIST's website is listed below: 
- Correct destination: [https://www.idmanagement.gov/program-managers/](https://www.idmanagement.gov/program-managers/).
- A redirect was created to send future visitors to the correct destination. 
- Please update your bookmarks.
- Note: this issue will be closed once the change has been `merged`.
> We've issued an update request to NIST to update [their page](https://csrc.nist.gov/news/2021/withdrawal-of-nist-special-pubs-800-15-25-and-32).
