### ISSUE TITLE
Create ILM Playbook page

### ISSUE THREAD

**Issue by TheInfinityBeyonder** [GSA/idmanagement.gov#993]
Add ILM playbook to playbook lists on site

- [x] Create Markdown file for ILM
- [x] Upload and arrange images
- [x] Add alt text to images
- [x] Add card/ image to playbooks page 
- [x] Add ILM to playbooks sidenav

**Comment by JBPayne007** [comment]
Image figures have been updated by Vanessa.

**Comment by JBPayne007** [comment]
Did we add the version history to state latest updates were completed in collaboration with USAID and Update the playbook card Latest Update:?

**Comment by JBPayne007** [comment]
Ok saw the version change.

**Comment by JBPayne007** [comment]
So a couple of things on this, The playbook chip date is 2024-18 this should be 2024-06 also the preview has two titles and could we add in the version history updates were completed in collaboration with USAID. Thank you

**Comment by claytonjbarnette** [comment]
@JBPayne007  @TheInfinityBeyonder @SuGhadiali 

Changes in PR #1007 

I updated the version history and fixed the title, since this was an update to an existing Playbook, the existing card and links still refer to it.

**Comment by claytonjbarnette** [comment]
This issue was resolved by 0625-ilm-playbook-updates-2 #1008 , Closing issue. 

@SuGhadiali 
@TheInfinityBeyonder 
@JBPayne007
